### ISSUE TITLE
Passing string literals through filters

### ISSUE THREAD

**Issue by tdammers** [yogthos/Selmer#100]
Given a context var `username`, and a filter `f`, this works:

    {{username|f}}

However, this doesn't:

    {{"tdammers"|f}}

The parser doesn't seem to recognize `"tdammers"` as a string literal, but it doesn't fail either; I suspect that it interprets `"tdammers"` as an identifier, and looking it up in the context yields `nil`.

This is both unexpected (because string literals do exist elsewhere in Selmer, and because it's a deviation from Django templates) and inconvenient (because it means that I cannot pass literals into a filter, e.g. for translation or formatting purposes).

**Comment by yogthos** [comment]
Seems reasonable, I just pushed out `0.9.2` with a fix, let me know if that addresses the issue.
