### ISSUE TITLE
Usage with placeholder text

### ISSUE THREAD

**Issue by Immortalin** [yogthos/Selmer#101]
Hi, is there a way to use this with placeholder text such as lorem Ipsum and programmatically disable it while trending a la enlive? This would allow the template file to be directly designed by the designer without having to worry too much about code.

**Comment by yogthos** [comment]
You could create a tag for this, for example:

```clojure
(add-tag!
  :placeholder
  (fn [args context-map content]
    (when (:dev context-map) (first args)))
  :endplaceholder)
```

```xml
{% placeholder %} lorem ipsum {% endplaceholder %}
```
Then if the `:dev` key is present in the context map the tag will inject its content into the template

**Comment by Immortalin** [comment]
Thanks
