### ISSUE TITLE
Usage with React

### ISSUE THREAD

**Issue by Immortalin** [yogthos/Selmer#102]
Hi, can Selmer be used with Reagent?

**Comment by yogthos** [comment]
Selmer can be used to setup the initial scaffolding for the page, but React maintains its own virtual DOM and will not work well with server side generated HTML in general.

**Comment by Immortalin** [comment]
So kioo is a the only alternative?

**Comment by yogthos** [comment]
For mixing HTML syntax with Reagent that's probably the best way to go.

**Comment by Immortalin** [comment]
This is really sad

**Comment by Immortalin** [comment]
I want to use Selmer as I don't like having to convert CSS selectors

**Comment by yogthos** [comment]
I just use the built in Reagent syntax and I find it works fine for me.

**Comment by Immortalin** [comment]
Can you elaborate? Is there any tutorials for this? I am really new to Clojure web development. I have read your book but it doesn't mention anything regarding this.

**Comment by yogthos** [comment]
I would recommend working through the examples on the [Reagent page](https://reagent-project.github.io/). I'd use the reagent template to keep things simple, e.g:

    lein new reagent myapp
    cd myapp
    lein figwheel

At this point you should be able to modify the files in the `src/cljs` source folder and see changes in the browser.
