### ISSUE TITLE
how to get a empty string when date is null

### ISSUE THREAD

**Issue by oscnet** [yogthos/Selmer#105]
```
expected: (= "" (render "{{d|date:\"yyyy-MM-dd\"}}" {:d nil}))
  actual: (not (= "" "2015-11-10"))
```
often a null day is not mean a current day.

**Comment by yogthos** [comment]
This looks like a bug to me, I'd also expect a nil date to return an empty string as opposed to the current time. I added a test and pushed out a fix to Clojars.
