### ISSUE TITLE
Recursive include results in stackoverflow

### ISSUE THREAD

**Issue by davisn** [yogthos/Selmer#106]
I tried to define a template to render a recursive tree structure using the `include` tag.  But no matter what I do, I get a StackOverflow.  It appears that Selmer ignores conditionals in this case.

For example, if `test.html` is

```
{% if false %}
{% include "test.html" %}
{% endif %}
```
This results in a `StackOverError`.

Here's a portion of the stack trace that seems relevant:

```
selmer.template-parser/preprocess-template  template_parser.clj:  252
    selmer.template-parser/insert-includes  template_parser.clj:   41
 selmer.template-parser/insert-includes/fn  template_parser.clj:   51
                                       ...                           
selmer.template-parser/preprocess-template  template_parser.clj:  252
    selmer.template-parser/insert-includes  template_parser.clj:   41
 selmer.template-parser/insert-includes/fn  template_parser.clj:   51
                                       ...                           
selmer.template-parser/preprocess-template  template_parser.clj:  252
    selmer.template-parser/insert-includes  template_parser.clj:   41
 selmer.template-parser/insert-includes/fn  template_parser.clj:   51
                                       ...                          
```

**Comment by yogthos** [comment]
This is working as designed as the `include` tags are resolved at compile time.

The way the parser works is that a template is compiled once and memoized for future use. All the `extends` and `include` tags are resolved at this time. The resulting template is used at runtime to evaluate the context map This is done for performance reasons, so this behavior is unlikely to be changed in the future.

**Comment by davisn** [comment]
Well, it appears that not only is the tag resolved at compile time, but actually expanded as well.  The way I envision this working is that a template is (for example) compiled to a function that takes a context map and spits back a string.  An `include` would then basically be a function call.  Is that not how Selmer works?

**Comment by yogthos** [comment]
That's not how Selmer works. Selmer parses the templates into a nester vector structure where each element is either a string of a function that accepts the context map. The layout of the page is represented by the vectors and this part is compiled once. Basically, `include` and `extends` tags are compile time, while the other tags are runtime.
