### ISSUE TITLE
Selmer pulls whole Clojurescript as a dependency

### ISSUE THREAD

**Issue by alexander-yakushev** [yogthos/Selmer#111]
Selmer depends on `json-html`, which in turn non-conditionally depends upon `clojurescript`. That's a little extreme to say the least. That`s ~15Mb extra weight in my uberjar. Adding an exclusion fixes that, but I don't feel that a templating library should depend upon whole another compiler. Can you perhaps make the Clojurescript dependency implicit?

**Comment by yogthos** [comment]
Ah yeah absolutely. ClojureScript should be provided in `json-html`. I just pushed out new versions with the fix.

**Comment by alexander-yakushev** [comment]
Thanks for the prompt response and fix! Happy upcoming New Year!

**Comment by yogthos** [comment]
no problem, and happy upcoming new year :)
