### ISSUE TITLE
Nested blocks in parent file causes the block.super on inner block to lose it's contents

### ISSUE THREAD

**Issue by saeidscorp** [yogthos/Selmer#128]
Hi, I was working on a project and was stuck for many hours figuring out why this code doesn't work as expected.

base.html
```
{% block outer %}
  {% block inner %}
    This text should be available via block.super
  {% endblock %}
{% endblock %}
```

derived.html
```
{% extends "base.html" %}
{% block inner %} {{ block.super}} {% endblock %}
```

When I render the `derived.html` file the result is empty, while when I remove the `outer` block it works fine.

Doesn't it have to retain its parent's contents? or what I'm missing?

**Comment by yogthos** [comment]
The `block.super` tag shows the content from the parent block. So, in your example the structure should be:

```
{% block outer %}
    This text should be available via block.super
    {% block inner %}
    {% endblock %}
{% endblock %}
```

**Comment by saeidscorp** [comment]
So what if I want to retrieve the `inner`'s contents?

**Comment by yogthos** [comment]
Currently, there isn't a way to get the content of the block you're rewriting. You could add a level of nesting to use super as a workaround for that.

**Comment by saeidscorp** [comment]
OK, Thanks!
