### ISSUE TITLE
Proposal: Allow setting *custom-resource-path* via render/parse opts

### ISSUE THREAD

**Issue by rwilson** [yogthos/Selmer#135]
The goal is to allow the resource path to be set on a per render basis, without side-effects affecting other renders. 

I came across this need because sometimes I render HTML and sometimes plain text, and sometimes its for a HTTP response and other times for an email. The templates are organized in a file hierarchy something like this:
```
resources/
    templates/
        email/
            html/
                layouts/
                ...
            text/
                ...        
        www/
            html/
                layouts/
                ...
            text/
                ...
```

Using `set-resource-path!` doesn't work for anything more narrow than "resources/templates/", because it alters the root binding, which is problematic for concurrent renders with different resource paths.

The PR for this won't eliminate `set-resource-path!`, it will just add `*custom-resource-path*` to the bindings settable by ops to the `parse` fn.

**Comment by rwilson** [comment]
Accidental close, reopening.

**Comment by yogthos** [comment]
This looks good to me, and [134](https://github.com/yogthos/Selmer/issues/134) does look like it was fat fingered. :)

**Comment by rwilson** [comment]
Closing since merging #136 addressed this.
