### ISSUE TITLE
double dotted escaped values failing with for loop

### ISSUE THREAD

**Issue by jstoner** [yogthos/Selmer#138]
Here's an example. 

```
user=> (require '[selmer.parser :as s])
nil
user=> (def page "{%for i in a..b/c%}<p>{{ i.d }}</p>{%endfor%}")
#'user/page
user=> (s/render page {:a.b/c [{:d "hi"} {:d "blah"}]})
""
user=> (def page "<p>{%for i in ab/c%}<p>{{ i.d }}</p>{%endfor%}")
#'user/page
user=> (s/render page {:ab/c [{:d "hi"} {:d "blah"}]})
"<p><p>hi</p><p>blah</p>"
```
It does seem to work in variable substitution and conditionals ({% ifequal a..b/c blah %} does work), so it doesn't seem generic to {% %} substitution.

**Comment by yogthos** [comment]
Yeah, that's not currently supported. As a workaround you could use [with](https://github.com/yogthos/Selmer#with) to create a local variable.

**Comment by jstoner** [comment]
Thanks, that worked.
