### ISSUE TITLE
if condition to compare key values

### ISSUE THREAD

**Issue by ishpreet06** [yogthos/Selmer#141]
When i use if condition like

 user=> (render "{% if f.b < 2  %} foo {% endif %}" {:f {:b 1 :c 2}})
" foo "

It is giving correct output.

But when i do 

user=> (render "{% if f.b < f.c  %} foo {% endif %}" {:f {:b 1 :c 2}})

NumberFormatException For input string: "f.c"  sun.misc.FloatingDecimal.readJavaFormatString (FloatingDecimal.java:2043)

It is throwing exception.

**Comment by yogthos** [comment]
implemented with https://github.com/yogthos/Selmer/commit/4e053680ef5936ed2157c6e1120426a3dbe39765

just pushed out `1.10.3` to Clojars with the feature
