### ISSUE TITLE
Can Zero as key of a hashmap?

### ISSUE THREAD

**Issue by jeffma** [yogthos/Selmer#149]
I render {{v.name}} {"0" "1.1" "1" "2.2" "name" "abc"} , it's ok,but {{v.0}} is not ok, it seems treat 0 as a array index,how can i get key 0's value?

**Comment by yogthos** [comment]
There isn't a way to render string keys that are numeric at the moment. Selmer attempts to parse numeric values. You could supply a map with numeric keys however:

```clojure
(render "{{v.0}}" {:v {0 "1.1" 1 "2.2" "name" "abc"}})
=>"1.1"
```

**Comment by jeffma** [comment]
thanks, i see
