### ISSUE TITLE
`sum` tag doesn't work with literal values

### ISSUE THREAD

**Issue by SevereOverfl0w** [yogthos/Selmer#150]
It appears it needs to use `compile-filter-body`

**Comment by yogthos** [comment]
It would be possible to check if the item is a number [here](https://github.com/yogthos/Selmer/blob/b64dfa156479814e850b98b844a2c54daa64e996/src/selmer/tags.clj#L213), but that would introduce problems for people using numeric keys as seen in [this issue](https://github.com/yogthos/Selmer/issues/149). Perhaps one way to do it could be to escape using something like `\1`.
