### ISSUE TITLE
[Question] How to print a map content if you don't know the keys? 

### ISSUE THREAD

**Issue by shandanjay** [yogthos/Selmer#151]
hi @yogthos I have question about forloop. How do you loop through map keys if you don't know the keys in Selmer ❓

**Comment by yogthos** [comment]
You can iterate over a map, and each element is going to be a vector of form `[k v]`:

```clojure
(render "{% for i in m %} key: {{i.0}} value: {{i.1}} {% endfor %}" {:m {:foo "hello" :bar "world"}})
=> " key: :foo value: hello  key: :bar value: world "
```

**Comment by shandanjay** [comment]
Perfect! It's the solution I was looking exactly.

@yogthos I really appreciate your projects, specially #Luminus. 

Thank you.

**Comment by yogthos** [comment]
👍
