### ISSUE TITLE
using two different resource paths can lead to improper cache behaviour

### ISSUE THREAD

**Issue by SVMBrown** [yogthos/Selmer#152]
If two templates have the same 'filename' in different custom resource paths, they collide in the cache.

I tested in the repl as follows:

```clojure
;; write initial templates
(spit (io/resource "foo.html") "foo {% include \"bar.html\" %}")
(spit (io/resource "bar.html") "bar")
(spit (io/resource "baz/foo.html") "collision!")

;; check foo
(render-file "foo.html" {})
;=> "foo bar"

;; modify included template
(spit (io/resource "bar.html") "baz/foo.html collided causing recompilation")

;; foo is unchanged (as expected)
(render-file "foo.html" {})
;=> "foo bar"

;; baz/foo.html collides with foo.html
(render-file "foo.html" {} {:custom-resource-path (io/resource "baz/")})
;=> "collision!"

;; foo now reflects changes to bar.html (Cache was unexpectedly busted)
(render-file "foo.html" {})
;=> "foo baz/foo.html collided causing recompilation"

```

I suspect that this problem could be much worse in a jar where all `last-updated` values are `-1`, but I haven't tested that aspect.

**Comment by yogthos** [comment]
Makes sense. If you have an idea for handling this scenario I'm open to a PR. :)

**Comment by SVMBrown** [comment]
I can strip down the PR to just include the use of resource-path as a key if you'd rather not have the changes to the resource-path fn and the signature of render-file, just let me know =)

**Comment by yogthos** [comment]
I think renaming it is the way to go, calling it filename would be misleading. :)

**Comment by yogthos** [comment]
and new version is up on Clojars :)

**Comment by SVMBrown** [comment]
sounds good! Do you think filename-or-URL is too blunt?

**Comment by yogthos** [comment]
no harm in being explicit
