### ISSUE TITLE
Dynamic usage of {% style %} and {% script %} tags?

### ISSUE THREAD

**Issue by mt0erfztxt** [yogthos/Selmer#157]
I've tried to use `{% script %}` and `{% style %}` tags inside `{% for %}` tag but it seems like vars doesn't expanded in these tags:
```clojure
(require '[selmer.parser :as parser])

(parser/render "{% for path in paths %}{% style {{path}} %}{% endfor %}" {:paths ["path/to/foo" "path/to/bar"]})
;; "<link href=\"{path rel=\"stylesheet\" type=\"text/css\" /> %}<link href=\"{path rel=\"stylesheet\" type=\"text/css\" /> %}"

;; Wrapping var in double quotes leads to exception.
(parser/render "{% for path in paths %}{% style \"{{path}}\" %}{% endfor %}" {:paths ["path/to/foo" "path/to/bar"]})
;; Exception malformed tag arguments in  style "{{path  selmer.util/check-tag-args (util.clj:81)
```
Are these tags support only raw string as argument? If so, what is a preferred way to accomplish dynamic rendering of style and script tags in Selmer?

P.S. I can construct plain old HTML `<link/>` and `<script/>` tags manually but then `{% style %}` and `{% script %}` tags looks a little redundant.

**Comment by yogthos** [comment]
Constructing plain HTML would be the way to go right now. I would be open to a pr to handle non-string arguments, you can see the implementation [here](https://github.com/yogthos/Selmer/blob/7fb60cb121472e83188713aaee69eae8fbb1c4c8/src/selmer/tags.clj#L273), and it should be easy to update it to handle dynamic params as well.

**Comment by mt0erfztxt** [comment]
Thank you for quick response. I would use plain HTML tags for now and plan to see (in spare time) how it can be implemented for dynamic arguments.

**Comment by mt0erfztxt** [comment]
For those who came here with same question as I did, the answer is - dynamic parameters work since v1.11.1.
