### ISSUE TITLE
{% for a in nil %} should call the missing-value-formatter

### ISSUE THREAD

**Issue by rutchkiwi** [yogthos/Selmer#165]
Hi! First of all thanks for making this library! It's really nice to work with and I'm using it with great results in a project at my company.

Now, to the issue at hand:
In said project we have a selmer.util/set-missing-value-formatter! set, so that we don't forget to pass in some variable. However, it does not seem to work for `for` tags. 

For example, if I pass nothing in  the context map like so: `(selmer/render-file "template.html" {})`
with template.html beeing:
```
{% for c in notthere %}
{% endfor %}
``` 
The missing value formatter is not called, and the template renders nothing. This is what I would expect if I had called it with `(selmer/render-file "template.html" {:notthere []})` but not giving any value seems like it should be an error.

Would you be open to a PR if I managed to figure something out? Any pointer would be appriciated in that case.

Thanks!

**Comment by yogthos** [comment]
Hi,

A PR for having the `for` tag respect missing values would be welcome. A good place to start looking would be [here](https://github.com/yogthos/Selmer/blob/771fd6e66f4231cb4fe8b219afc367d846dabc61/src/selmer/tags.clj#L39) to see what the `for` tag is doing. The missing value formatter is only used in filters [here](https://github.com/yogthos/Selmer/blob/140c9becfc6c055d62ac9ae83365796fd3c68764/src/selmer/filter_parser.clj#L172). Since the filters never end up being called when the key isn't supplied, it never ends up being triggered.

**Comment by rutchkiwi** [comment]
Great, I'll have a look. Thanks for the quick reply!

**Comment by yogthos** [comment]
Thanks, and just pushed out a new release with the fix.

**Comment by rutchkiwi** [comment]
Amazing! Thanks a lot! :)

**Comment by rutchkiwi** [comment]
Hmmm using it in my own project, it turned out to be quite annoying that it's calling *missing-value-formatter* with the tag just beeing ":for". For instance, some files had 4 for loops in them and it did not specify which one was getting a nil value. Do you think it should be changed to something else like ```{:tag-type :for, :arg "notthere"}```?

I presume at least some people will have depended on the old behaviour of just returning "", so might be helpful for these people when they upgrade.

**Comment by yogthos** [comment]
Yeah, it would be nice to do this in a backwards compatible way. Perhaps the `missing-value-formatter` could select on the type. If you pass it a function then it retains current behavior, and if you pass it a map then it can use the additional data. If that sounds reasonable, I'd be ok adding that in. Would be good to document this in the docs as well.

**Comment by rutchkiwi** [comment]
Hmm I might be missing something, but isn't the missing-value-formatter already supposed to accept a map? https://github.com/yogthos/Selmer#missing-values

Or do you mean something like this:
```
(selmer.util/set-missing-value-formatter! {:tags-to-do-stuff-with [:normal-tags :for]
                                                                    :formatter missing-value-fn)```?

**Comment by yogthos** [comment]
Yeah something like that, maybe could use a map of tag-type->tag-formatter:

```clojure
(set-missing-value-formatter!
  {:for for-format
   ...
   :default default-format})
```

**Comment by rutchkiwi** [comment]
Hmmm my concern was primarily with the fact that the missing-value-formatter currently does not know which for loop got a nil value, so if there are many for loops in the template it gets quite confusing to know which one. I'm quite sure that could be sorted out quite easily by passing in that information on line https://github.com/yogthos/Selmer/blob/c103aa807043987dc498abf48f851128cdd04285/src/selmer/tags.clj#L54.

The backwards-compatability is a different issue and harder to resolve! I'd argue that it should probably be fine to leave it as is, as only people who've set a missing value formatter will be affected (and these people probably want the new behaviour, that is, calling the missing-value-formatter when the thing to for loop over is missing). Having multiple missing-value-formatters probably opens up a big chance that people forget to set the missing-for-formatter and thus get the same problem as before.

I can make a PR for the first problem to show you what I mean if that helps?

**Comment by rutchkiwi** [comment]
there, I think that fixes the first problem. I think it'd be good to get that in, regardless of the backwards compatibility issue. I should have thought a bit more about if for that first PR, sorry!

**Comment by yogthos** [comment]
No problem, and I agree that it shouldn't be a problem for existing users. Could you update the docs as well to note the behavior. I can push out a new release after.

**Comment by rutchkiwi** [comment]
I've updated the readme now to make it a bit more clear that for loops are included. I don't think there should be any more stuff to update since I intentionally made it work like the docs said in the first place. Happy to update it some more if you had somewhere in mind where the docs need to change further?

**Comment by yogthos** [comment]
I think we're good, just pushed out a new release to Clojars, thanks again for spearheading the change. :)

**Comment by rutchkiwi** [comment]
great, thank you! :)
