### ISSUE TITLE
Documentation outdated or bug?

### ISSUE THREAD

**Issue by bitti** [yogthos/Selmer#169]
This example in https://github.com/yogthos/Selmer#str

    So you can do crazy stuff like: (render "{{people|length-is:2|str|join:\"-\"}} lad{{people|pluralize:\"y\":\"ies\"}}" {:people [1 2]}) => "t-r-u-e ladies"

yields `[-:-s-a-f-e- -t-r-u-e-] ladies` for me. But if I insert a `last|` before the `str` as in

    (render "{{people|length-is:2|last|str|join:\"-\"}} lad{{people|pluralize:\"y\":\"ies\"}}" {:people [1 2]})

it works for me as advertised. Is this expected and the documentation is just outdated?

**Comment by yogthos** [comment]
Ah yeah that's a docs typo, thanks for the heads up.
