### ISSUE TITLE
Bug with boolean values

### ISSUE THREAD

**Issue by ilevd** [yogthos/Selmer#172]
I just started updating my project dependencies, from [selmer "0.8.2"] to [selmer "1.11.6"] and found this:
```
(selmer.parser/render "Hello {{name}}" {:name true})
=> "Hello true"
(selmer.parser/render "Hello {{name}}" {:name false})
=> "Hello "
```
I'm inserting boolean value to js code, and it's not working now, so it seems there is a bug.

**Comment by yogthos** [comment]
Thanks for the heads up, just pushed out `1.11.7` with the fix.
