### ISSUE TITLE
Use in ClojureScript

### ISSUE THREAD

**Issue by jerger** [yogthos/Selmer#173]
Did anybody try to use selmer in ClojureScript already?
Are there any hard clj dependencies?

**Comment by yogthos** [comment]
In theory it should be possible to port selmer to cljs, but it does have some Java dependencies such as clj-time. It also heavily relies on Java pushback reader, so the porting effort would be non-trivial.

**Comment by jerger** [comment]
Thanx for your fast answer ... "not trivial" sound like it's a good idea to get some more experience with cljs before starting a try :-)
