### ISSUE TITLE
the `default` filter does not work if you have a missing-value-formatter that throws exceptions

### ISSUE THREAD

**Issue by rutchkiwi** [yogthos/Selmer#175]
For example, if I've done this (which I've found to be a really useful way to catch errors):
```
(defn- missing-value-fn [tag context-map]
  (throw (Exception. (str "Selmer template error: " tag " was null."))))

(selmer.util/set-missing-value-formatter! missing-value-fn)
```

now
```
(selmer/render "{{name|default:\"I <3 ponies\"}}" {}) 
```
throws
```
Exception Selmer template error: {:tag-type :filter, :tag-value "name|default:\"I <3 ponies\""} was null.  medino-web.handler/missing-value-fn (handler.clj:44)
```

I've found myself wanting to use the default filter loads of times, but now I'm stuck writing clunky if-s to get around it. 

Of course I'm happy to make a PR, but I tried and got quite lost so I'd really appriciate some help!

Also thanks again for writing this really nice library, we're using it a lot at my work!

**Comment by yogthos** [comment]
Thanks for the heads up. I agree that would be a better behavior, and I'll try taking a look shortly.

**Comment by yogthos** [comment]
Here's what I'm thinking so far, I could extract the [filter splitting logic](https://github.com/yogthos/Selmer/blob/78d8021510361e15960cb52afad9fc274c96685e/src/selmer/filter_parser.clj#L160) into a standalone function:

```clojure
(defn split-value [s]
  (->> s
       (s/trim)
       ;; Ignore pipes and allow escaped doublequotes inside doublequotes
       (re-seq #"(?:[^|\"]|\"[^\"]*\")+")))
```
then you'd be able to do the following in the `missing-value-fn`:

```clojure
(defn- missing-value-fn [{:keys [tag-type tag-value] :as tag} context-map]
  (or
    (when-let [filters (->> (when (= :filter tag-type) tag-value)
                            (selmer.filter-parser/split-value)
                            (rest)
                            (map selmer.filter-parser/filter-str->fn)
                            (not-empty))]
      (or (reduce
            (fn [val filter]
              (filter val context-map))
            nil filters)))
    (throw (Exception. (str "Selmer template error: " tag " was null.")))))

(selmer.util/set-missing-value-formatter! missing-value-fn)

(render "{{name|default:\"I <3 ponies\"|upper}}" {})
=> "I <3 PONIES"

(render "{{name}}" {})
 => java.lang.Exception: Selmer template error: {:tag-type :filter, :tag-value "name"} was null.
```

Let me know if that looks reasonable to you.

**Comment by rutchkiwi** [comment]
Thanks a lot for the quick reply!

Yeah that does work perfectly!

**Comment by yogthos** [comment]
Ok great, just pushed out `1.11.8` with the change. :+1:

**Comment by rutchkiwi** [comment]
Okay pulled it and it works perfectly! Thanks a lot, this will really help me out! :D

Also thanks again for writing this great library!

**Comment by yogthos** [comment]
Glad to hear everything's working, and you're welcome. :)
