### ISSUE TITLE
A couple of filters which are useful to me

### ISSUE THREAD

**Issue by simon-brooke** [yogthos/Selmer#177]
Filters which I find useful and which may be useful to others. Sanity-checking the input format should prevent them being used for cross-site scripting attacks. You may (or may not!) want to add them to the 'standard' filters.

```clojure
(ns adl-support.filters
    (:require [clojure.string :as s]
              [selmer.filters :as f]
              [selmer.parser :as p]))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;
;;;; adl-support.filters: selmer filters required by ADL selmer views.
;;;;
;;;; This program is free software; you can redistribute it and/or
;;;; modify it under the terms of the MIT-style licence provided; see LICENSE.
;;;;
;;;; This program is distributed in the hope that it will be useful,
;;;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;;;; License for more details.
;;;;
;;;; Copyright (C) 2018 Simon Brooke
;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


(def *default-international-dialing-prefix* 
  "The international dialing prefix to use, if none is specified."
  "44")

(defn telephone 
  "If `arg` is, or appears to be, a valid telephone number, convert it into
  a `tel:` link, else leave it be."
  [^String arg]
  (let [number 
        (s/replace 
         (s/replace 
          arg 
          #"^0" 
          (str "+" *default-international-dialing-prefix* "-")) 
         #"\s+" "-")]
    (if (re-matches #"[0-9 +-]*" arg)
      [:safe (str "<a href='tel:" number "'>" arg "</a>")]
      arg)))


;; (telephone "07768 130255")
;; (telephone "Freddy")

(defn email 
  "If `arg` is, or appears to be, a valid email address, convert it into
  a `mailto:` link, else leave it be."
  [^String arg]
  (if (re-matches #"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,6}$" arg)
    [:safe (str "<a href='mailto:" arg "'>" arg "</a>")]
    arg))


;; (email "simon@journeyman.cc")
;; (email "simon@journeyman")
;; (email "simon@journeyman.cc.")
       
(f/add-filter! :telephone telephone)

(f/add-filter! :email email)
   
;; (p/render "{{p|telephone}}" {:p "07768 130255"})
```

**Comment by yogthos** [comment]
Thanks, those definitely look handy. [Here's](https://github.com/yogthos/Selmer/commit/fc22465996694bf4cc9ca3af8d2a4cd833c61523) what I'm thinking so far. I'd rather have validation be a flag, and throw an error if it's enabled and fails. I was also thinking that it might be better to add the dialing prefix outside selmer by preprocessing the context map.

**Comment by simon-brooke** [comment]
I could get the local dialing prefix from [PhoneNumberUtil](https://github.com/googlei18n/libphonenumber), but that means dragging in a whole other library which most users of Selmer will never use, so I'm rather against that - it's code bloat. But in an international web, ignoring the international dialling code is risky - so I'm inclined to think that 'format as dialable number' ought to do that.

Obviously it would be better to require the international code prefix when data is input than when data is output, but still...

My idea was filters which could be used for (e.g.) database fields to make them clickable if they conformed to a pattern, but left them 'as is' if they didn't conform.

I'll think about this further and try to submit an improved version - would you prefer it as a pull request?

**Comment by yogthos** [comment]
Yeah I'd rather avoid pulling a whole library in for this, and I'm not sure I like having a random global variable for the dialing prefix since it's pretty specific to the filter. It might be better to keep the phone filter generic, and wrap it with a custom one in the application:

```clojure
(f/add-filter!
  :international-phone
  (fn [phone]
    (f/call-filter :phone (s/replace phone #"^0" (str "+" international-dialing-prefix "-")))))
```
And feel free to use the branch I started for this.

**Comment by simon-brooke** [comment]
OK, good. I'll have a look at this once I've got oauth working (!)

**Comment by yogthos** [comment]
:+1:

**Comment by yogthos** [comment]
closed by https://github.com/yogthos/Selmer/pull/180
