### ISSUE TITLE
Query string for {% script %}?

### ISSUE THREAD

**Issue by poulinjulien** [yogthos/Selmer#181]
I would like to add a simple cache busting mechanism for the scripts using the application version like so:

````js
<script src="bundle.js?v={{version}}"></script>
````
Is there a way to do that with the [script](https://github.com/yogthos/Selmer#script) tag?

**Comment by yogthos** [comment]
You can specify a `:path` key in the context as follows:

```clojure
(render "{% script path %}" {:path (str "/js/site.js?v=" version)})
```

**Comment by poulinjulien** [comment]
OK, so it cannot be done inline.

Thanks.
