### ISSUE TITLE
include doesn't work with render, only render-file

### ISSUE THREAD

**Issue by lxsli** [yogthos/Selmer#182]
Adding this `is` causes the test to fail:

```
diff --git a/test/selmer/core_test.clj b/test/selmer/core_test.clj
index f9ff252..3719ed5 100644
--- a/test/selmer/core_test.clj
+++ b/test/selmer/core_test.clj
@@ -102,6 +102,8 @@
     (is
       (= (fix-line-sep "Base template.\n\n\t\n<p></p>\n\n\n")
          (render-file "templates/child.html" {})))
+    (is (= "base tempate hello"
+           (render "base tempate {% include \"templates/inheritance/include/snippet.html\" %}" {})))
     (is (= "base tempate hello"
            (render-file "templates/inheritance/include-snippet.html" {})))
     (is
```

The contents of the string I'm rendering is exactly the contents of the file.

The error:

```
ERROR in (inheritance) (parser.clj:146)
expected: (= "base tempate hello" (render "base tempate {% include \"templates/inheritance/include/snippet.html\" %}" {}))
  actual: java.lang.Exception: unrecognized tag: :include - did you forget to close a tag?
 at selmer.parser$expr_tag.invokeStatic (parser.clj:146)
    selmer.parser$expr_tag.invoke (parser.clj:143)
    selmer.parser$parse_tag.invokeStatic (parser.clj:164)
    selmer.parser$parse_tag.invoke (parser.clj:160)
    selmer.parser$add_node.invokeStatic (parser.clj:226)
    selmer.parser$add_node.invoke (parser.clj:221)
    selmer.parser$parse_STAR_.invokeStatic (parser.clj:238)
    selmer.parser$parse_STAR_.invoke (parser.clj:228)
    selmer.parser$parse_input.invokeStatic (parser.clj:260)
    selmer.parser$parse_input.doInvoke (parser.clj:257)
    clojure.lang.RestFn.invoke (RestFn.java:423)
    selmer.parser$parse.invokeStatic (parser.clj:293)
    selmer.parser$parse.doInvoke (parser.clj:267)
    clojure.lang.RestFn.invoke (RestFn.java:442)
    selmer.parser$render.invokeStatic (parser.clj:105)
    selmer.parser$render.doInvoke (parser.clj:103)
    clojure.lang.RestFn.invoke (RestFn.java:425)
    selmer.core_test$fn__3392$fn__3425.invoke (core_test.clj:106)
    selmer.core_test$fn__3392.invokeStatic (core_test.clj:105)
    selmer.core_test/fn (core_test.clj:67)
    ...
```

**Comment by yogthos** [comment]
That's by design. The `render` function is only meant to be used with one off string templates, and it's not efficient because it doesn't memoize and parses the template each time it's run.

**Comment by lxsli** [comment]
Not quite sure what to say to that. It's pretty weird (and undocumented
afaict) that the render method doesn't support all directives. I only ever
parse each template once so I don't need memoization. Also I'm parsing
one-off snippets out of a larger file so using the file-based one would be
super inconvenient for me, I would have to write a temporary file every
time. I've had to invent my own syntax on top to support includes, which
isn't hard or anything but it's disappointing that Selmer can't do this for
me.

**Comment by yogthos** [comment]
You could just inject the includes via the context map in your case:

```clojure
(selmer.parser/render "{{file-include|safe}}"
  {:file-include (selmer.parser/render-file "templates/inheritance/include/snippet.html" {})})
```

**Comment by lxsli** [comment]
How do I know which file to provide ahead of time? To give a bit more info
about my usecase, I'm processing Adoc files containing structured blocks.
Some blocks (EG a graphql request) are run through Selmer before being sent
off. Sometimes I want to POST a large file so rather than include that file
inline in my Adoc, I'd like to use a file include. But people will write
new adoc files all the time and potentially new POSTable files. I suppose I
could demand all files are in one directory and throw them all in the
context, that'd work. Thanks.

**Comment by yogthos** [comment]
You could also make a custom tag or filter that implements the include functionality for your case.
