### ISSUE TITLE
wrap-error-page middleware should support 3-arity besides 1-arity

### ISSUE THREAD

**Issue by mping** [yogthos/Selmer#184]
The `wrap-error-page` should support 3-arity also: https://github.com/ring-clojure/ring/wiki/Concepts#handlers

I can hack a quick PR if you'd like

**Comment by yogthos** [comment]
Thanks, that would be great!

**Comment by yogthos** [comment]
implemented in [1.12.8](https://github.com/yogthos/Selmer/commit/090cac1ebc2d7223cfe40d5a8012b549ce51d832)

**Comment by mping** [comment]
👍
