### ISSUE TITLE
Unexpected [:safe "50"] return value

### ISSUE THREAD

**Issue by devth** [yogthos/Selmer#195]
```clojure
(render "{{10|multiply:1.8|add:32}}" {})

=> "[:safe 50.0]"
```

So if I try to round it throws:

```clojure
(render "{{10|multiply:1.8|add:32|round}}" {})
=> On filter body '10|multiply:1.8|add:32|round' and filter 'round' this error occurred:For input string: \"[:safe 50.0]\"
```

Using `[selmer "1.12.9"]`

**Comment by yogthos** [comment]
Thanks for the heads up, just pushed out an update with `1.12.11` to update the `add` and `round` filter so that it returns the value directly. Filters shouldn't be wrapping the values with safe filter in general since that doesn't compose.

**Comment by devth** [comment]
Thanks! I will test it out soon.
