### ISSUE TITLE
List of all variables in template?

### ISSUE THREAD

**Issue by joelash** [yogthos/Selmer#202]
Wondering what the best way, if any, to see a list of all variables present in a template? I've used `parse` to create a list of nodes and started looping through their metadata; however this leaves out anything nested inside of a block.

**Comment by yogthos** [comment]
Hi,

There isn't any direct support for seeing all the declared variables, so running `parse` is the best option at the moment. You could try running `parse-file` instead to inject the block content and create a single template that should contain all the nodes.

**Comment by joelash** [comment]
Thanks @yogthos, however I think I may have misspoken. I cannot seem to find any information in `(:tag (meta node))` when parsing something like: 

```
"<div>Hello {{name}}</div>
{% ifequal \"foo\" x %}
   Happy {{day-of-week}}
{% endifequal %}"))
```

I'd expect to somehow find the information for `day-of-week`, but it doesn't seem to be easily found.

**Comment by yogthos** [comment]
Ah yes, unfortunately it's not possible to traverse the nodes generated by the parse function, so anything captured inside them becomes opaque. It looks like this functionality would require a new function that works similarly to parse to walk the template and generate the metadata.

**Comment by joelash** [comment]
@yogthos here's a [gist](https://gist.github.com/joelash/4abf02d990c9173f4af64f5c4cf3f9b1) with the code I wrote. I had to get crazy and use a `with-redefs` as well as it's probably not working 100%. If I worked to make this work a bit better and without the `with-redefs` by being first class, would you accept a PR? Do you have better ideas an approach?

**Comment by yogthos** [comment]
Your approach looks pretty reasonable to me, and a PR to make this first class would be fantastic.

**Comment by avallark** [comment]
@joelash , just letting you know that there are more people who'd appreciate your PR. Thanks mate.

**Comment by joelash** [comment]
@avallark I’m working on it now. Hopefully should have a PR ready next week

**Comment by joelash** [comment]
Created PR: https://github.com/yogthos/Selmer/pull/208

**Comment by yogthos** [comment]
@joelash just pushed out 1.12.16 with the enhancement, thanks again for spearheading this. 🎉

**Comment by joelash** [comment]
@yogthos Thanks!
