### ISSUE TITLE
Question: How can i display session variables in Jinja2

### ISSUE THREAD

**Issue by avallark** [yogthos/Selmer#204]
Hi, 

Thank you for Selmer. Makes life so much easier. 

I come from a python / Flask background, there I used to be able to use a Jinja2 variable as {{request.session}} to display my session variables.

Is there an equivalent, I can use with selmer?

**Comment by yogthos** [comment]
So, some good news bad news on that front. There's no built in way to get the info currently, but [this](https://github.com/yogthos/Selmer/issues/202) issue has an example and a PR is planned for adding this directly in the library.

**Comment by avallark** [comment]
Thank you mate. Appreciate the response. I will wait for a release post that PR.

**Comment by yogthos** [comment]
Just released 1.12.16 with the [PR](https://github.com/yogthos/Selmer/pull/208) merged. There's now a `known-variables` function in the `selmer.parser` namespace, so you can run `(slemer.parser/known-variables "{{name}}")` to see the declared variables in the template.

**Comment by avallark** [comment]
Sorry to reopen this, but i do not understand this usage. What i wanted is to figure out how to access the request session variables within jinja 2. 
Could you please explain, how to get from this to where I want to be? 
Thanks so much.

**Comment by yogthos** [comment]
I'm not really familiar with jinja, so I don't quite follow the question. Any variables passed to Selmer would be declared in the map that's passed as the argument when rendering the template.
