### ISSUE TITLE
Type hint ^java.net.URL missing on selmer.util

### ISSUE THREAD

**Issue by linca-apricot** [yogthos/Selmer#210]
selmer 1.12.15, 1.12.16 has error on NativeImage (GraalVM requires type hint to avoid reflection).

```
Exception in thread "main" java.lang.IllegalArgumentException: No matching field found: getPath for class java.net.URL
...
at selmer.util$resource_last_modified.invokeStatic(util.clj:187)
        at selmer.util$resource_last_modified.invoke(util.clj:184)
...
```

https://github.com/yogthos/Selmer/blob/55188100144567961c7a4216337592705e08d950/src/selmer/util.clj#L184-L187

selmer 1.12.14 is OK.

https://github.com/yogthos/Selmer/blob/1991ecf9208f405a87ae93d0c9a0a4e049e126f9/src/selmer/util.clj#L172-L175

**Comment by yogthos** [comment]
So, it looks like the resource should always be a URL now. I checked in an update with a type hint [here](https://github.com/yogthos/Selmer/blob/4fdf5b546d6afb2e5cea98adc9424694f6ca5e64/src/selmer/util.clj#L178). Let me know if that solves the issue. As a side note, could you share your script for building the native image. I couldn't get it to work locally myself.

**Comment by linca-apricot** [comment]
I use your updated code selmer-1.12.17 by https://github.com/kumarshantanu/lein-localrepo and it is OK.

### Native Image Usage

Get GraalVM Community Edition 19.2.0 https://github.com/oracle/graal/releases

and install native-image

```bash
gu install native-image
```

create Jar and native-image

```bash
lein uberjar
native-image --no-server -jar target/hello-1.0.0-standalone.jar --report-unsupported-elements-at-runtime --initialize-at-build-time
```

**Comment by yogthos** [comment]
Great, I just pushed out `1.12.17` to Clojars with the fix, and thanks for the example. 👍
