### ISSUE TITLE
with clauses with = signs does not work

### ISSUE THREAD

**Issue by rutchkiwi** [yogthos/Selmer#211]
Hi!

I'm having an issue with some code like the following:

```clojure
(selmer/render "{% with math=\"1+1=2\" %}{{ math }}{% endwith %}" {})
```

I'd expect this to work even if the string passed in contains = signs - in the acual code I'm working on I'm passing in some links wich break when I introduce query params.

I can definitly help out with making a PR if I can get some guidance on where to start. Thank you!

**Comment by yogthos** [comment]
Selmer does escaping by default, so that might be what's causing the issue here.

**Comment by rutchkiwi** [comment]
Sorry - I should have given more info about the error. It's actually throwing and exception, like so:

```clojure
(selmer/render "{% with math=\"1+1=1\" %}{{ math }}{% endwith %}" {})
Execution error at selmer.tags/compile-args (tags.clj:260).
invalid arguments passed to 'with' tag: clojure.lang.LazySeq@c183ec23
```
I will dig around a bit in the code to see if I can find the exact issue and hope to produce a PR.

**Comment by rutchkiwi** [comment]
Strangely enough this works fine for the `{% include .. with %}` tag

**Comment by yogthos** [comment]
Ah yeah, the include tag has a separate implementation that runs when the templates are parsed. And the PR looks good, thanks for getting that in. I just pushed out `1.12.18` with the fix.

**Comment by rutchkiwi** [comment]
Thanks for that, and thanks for the fast response! :)
