### ISSUE TITLE
Upgrade 1.12.12 -> 1.12.18 broke Cryogen's use of file:some/relative/dir

### ISSUE THREAD

**Issue by holyjak** [yogthos/Selmer#213]
[Cryogen](http://cryogenweb.org/) sets the Selmer custom path like this

https://github.com/cryogen-project/cryogen-core/blob/2f0d5a4545e138c46383a947f562d4078fda02cd/src/cryogen_core/compiler.clj#L583 

to point to `./themes/<theme name>`. The problem is that after upgrade to .18 this stopped working having the desired effect, likely due to 

https://github.com/yogthos/Selmer/blob/12c0844df484593869e85728f9403aadd8acb010/src/selmer/util.clj#L173

which previously wasn't so strict and did accept `file:` without a leading `\`:

https://github.com/yogthos/Selmer/blob/0503ca304398fe19b128db663ea1c80fc9c6e586/src/selmer/util.clj#L169

I do not know Selmer well enough to understand whether it is a defect there or (more likely) it used to work only by accident (since `file:relative/path/..` does look _wrong_ to me). So this is mainly to notify you that some users might run into the issue with this "patch" version change...

**Comment by yogthos** [comment]
Looks like the way Cryogen sets custom path should be updated to create a string that can be parsed by `URL`.

**Comment by holyjak** [comment]
thank you, fixed!
