### ISSUE TITLE
{% if true %} is very counter intuitive

### ISSUE THREAD

**Issue by simon-brooke** [yogthos/Selmer#214]
If run from the REPL, the behaviour of `{% if true %}` is extremely unexpected:
```
user=> (render "{% if true %}foo{% endif %}" {})
""
```

This isn't actually the bug I was trying to track down, what I'm trying to track down is why under some circumstances passing a boolean to Selmer's `if` appears to throw a class cast exception, but it's an interesting feature.

**Comment by simon-brooke** [comment]
also counter-intuitive:

```
user=> (render "{% ifequal foo.bar true %}foo{% endifequal %}" {:foo {:bar true}})
""
```
and also
```
user=> (render "{% ifequal foo.bar|str true|str %}foo{% endifequal %}" {:foo {:bar true}})
""
```

**Comment by simon-brooke** [comment]
D'oh!

The thing which was causing a class cast exception was typing

```
{% if upload.is-image %)
```

instead of
```
{% if upload.is-image %}
```

Perils of working when too tired. If I can write a patch to catch this exception and produce some sort of useful error message, would you accept it?

**Comment by yogthos** [comment]
A patch sounds great, and completely agree that a useful error message would be helpful. Let me know if you need a hand with anything.

**Comment by simon-brooke** [comment]
H'mmmm... it's more complex than that. When I do this in the REPL I get a reasonably sensible exception thrown:

```
user=> (render "{% if upload.is-image %)Hello dere{% endif %}" {:upload {:is-image true}})
Exception No closing tag found for :if  selmer.parser/tag-content (parser.clj:200)
```

If I reproduce exactly the state of the template I had when I was getting the ClassCastException (scratch.txt, attached) I get a different, but still sensible, error message:

```
user=> (def scratch (slurp "../smeagol/resources/templates/scratch.txt"))
#'user/scratch
user=> (render scratch {:uploads [{:is-image true :size :med :filename "foo.png" :resource "content/uploads/foo.png"}]})
Exception unrecognized tag: :extends - did you forget to close a tag?  selmer.parser/expr-tag (parser.clj:155)
```

So what this looks like was rather than a bug in Selmer, the bug was in me failing to correctly handle exceptions thrown back to me. D'oh!

[scratch.txt](https://github.com/yogthos/Selmer/files/4198228/scratch.txt)

**Comment by yogthos** [comment]
Ah no worries, glad to hear it's all working though. :)
