### ISSUE TITLE
Short-form comments inside other tags don't get removed

### ISSUE THREAD

**Issue by rutchkiwi** [yogthos/Selmer#220]
Hi Dmitri!

I'll just show some example code to illustrate the problem:

```
(selmer/render "{% if a %} some text {% comment %} comment! {% endcomment %} {% endif %}" {:a true})
=> " some text  "
```
Works great!

```
(selmer/render "{% if a %} some text {# comment! #} {% endif %}" {:a true})
=> " some text {# comment! #} "
```
now my comment is left in..

Is this a bug or am I doing something incorrectly? Thanks!

**Comment by yogthos** [comment]
Yeah, that looks like a bug with the short form comment implementation.

**Comment by rutchkiwi** [comment]
Ok - I will get a fix PR ready. Do you have any ideas or pointers of where I should start?

**Comment by yogthos** [comment]
Awesome, a PR would be fantastic, and [this PR](https://github.com/yogthos/Selmer/pull/113/files) is where the feature got added in initially, so probably a good place to start.
