### ISSUE TITLE
selmer can't find template under windows

### ISSUE THREAD

**Issue by markokocic** [yogthos/Selmer#231]
Since version 1.2.15 and newer selmer can't find a file resource template when run under Windows. 

Check Cryogenweb issue [204](/cryogen-project/cryogen/issues/204)

selmer 1.2.14 and older work fine.

**Comment by yogthos** [comment]
It looks like changing `"/"` to `java.io.File/separator` in [here](https://github.com/yogthos/Selmer/blob/3158cc87bbb42c5826ab5bc472ab179d4ab00624/src/selmer/parser.clj#L49) and [here](https://github.com/yogthos/Selmer/blob/3158cc87bbb42c5826ab5bc472ab179d4ab00624/src/selmer/util.clj#L168), might fix the issue. I don't have Windows available, so I'm not able to test this myself unfortunately. Would you mind trying out the change to see if that helps?

**Comment by markokocic** [comment]
Not really. Looks like the issue comes when mixing `/` and `\` when trying to resolve template file based on ` *custom-resource-path*` (e.g `"c:\dir\dir\themes\my"`) and resource `"/html/page.html"`.

**Comment by yogthos** [comment]
It doesn't look like anything should have changed around that between 1.2.14 and 1.2.15 releases, so a bit odd that this broke. Unfortunately, I can't really test this locally as I don't have Windows available. I'd be glad to help with a PR and do a release if somebody with Windows can take a look at this.

**Comment by brunchboy** [comment]
A Windows-based user of my own project which is in the process of adding Selmer to do some really cool things ran into this as well. I will try to fork Selmer tonight and make the changes you proposed; they seem to be on the right track. I have a Windows VM that I can test things within, so if changing Beat Link Trigger to use this fork fixes this problem, I will submit my changes as a PR.

**Comment by yogthos** [comment]
Awesome thanks!

**Comment by brunchboy** [comment]
Sadly, just replacing those two instances of `"/"` with `java.io.File/separator` was not enough to get things working. Any ideas what to look at next? Does maybe `append-slash` need to use it as well? I am so awkward and inefficient trying to do development and testing in my Windows VM, sadly. I guess I will try to add a bunch of logging and see if I can make any headway. More hints would be welcome!

**Comment by brunchboy** [comment]
Ok, in Beat Link Trigger I can evaluate expressions, and I think this has revealed the problem. `selmer.util/*custom-resource-path*` is `C:\Users\James Elliott\Documents\OBS Overlay\Templates/`. The Windows drive letter is preventing the recognition of this as an absolute path. Researching ways people recognize these things…

**Comment by brunchboy** [comment]
Ok, the pull request is in. For now I am building snapshots of Beat Link Trigger against my own non-canonical fork, but please let me know when there is a new, canonical, non-snapshot release deployed and I will switch back. Thanks! 😄

**Comment by yogthos** [comment]
Great, everything looks to be working on my end as well. Thanks again for spearheading the fix. 🎉

**Comment by brunchboy** [comment]
My pleasure! Thanks for Selmer, it’s a delightful templating environment, and is going to enable my users to do some really creative and fun things with overlays showing their music player status and waveforms when live-streaming DJ performances.

**Comment by yogthos** [comment]
Thanks, really glad to hear it's been helpful. The project sounds pretty awesome by the way. :)
