### ISSUE TITLE
Can I create an add-tag! handler that can manipulate the contents/context-map before rendering the content in the block tag?

### ISSUE THREAD

**Issue by mlimotte** [yogthos/Selmer#236]
It seems that the content passed to an `add-tag!` handler is already parsed. I’d like to add a block tag that can manipulate the context-map (for the scope of that tag content) and render “afterward”.

Stated another way, I’d like to add a handler, similar to `selmer.tags/with-handler`.

Is it possible to add tags with that level of power?

**Comment by yogthos** [comment]
The tags are stored in an atom [here](https://github.com/yogthos/Selmer/blob/16114d767c8bdcc8af6abf8a657b2f8c839763c3/src/selmer/tags.clj#L391), and you can directly add a tag directly to the atom without  using `add-tag!` and implement a custom version of [tag-handler](https://github.com/yogthos/Selmer/blob/master/src/selmer/tags.clj#L435) with the desired behavior.

```clojure
(swap! selmer.tags/expr-tags assoc :foo your-custom-tag-handler)
```

if the tag has a corresponding end tag, you'll also need to call `selmer.parser/set-closing-tags!`, e.g:

```clojure
(set-closing-tags! :foo [:endfoo])
```

**Comment by mlimotte** [comment]
Thank you! A bit verbose, but it looks like it will work for me.
Thanks for supporting this cool library.

**Comment by yogthos** [comment]
Perfect, and glad to hear it's coming in handy. :)
