### ISSUE TITLE
italicizing and bolding text mid-vector

### ISSUE THREAD

**Issue by sova** [yogthos/Selmer#238]
Hi I have a question, I have a vector of paragraphs (strings) but now I would like to italicize just certain words, is it possible to use filter in a way to inject italics or bold tags without incurring a large regex processing "tax?"

**Comment by yogthos** [comment]
Yup, you just have to mark the filter as safe to avoid escaping, e.g:

```clojure
(add-filter!
  :italics
  (fn [text] [:safe (str "<i>" text "</i>")]))

(render "{{shout|italics}}" {:shout "hello"})
```

**Comment by sova** [comment]
Excellent!  Thanks @yogthos
