### ISSUE TITLE
forloop.previous would be very useful for identifying same/changed values between iterations

### ISSUE THREAD

**Issue by seancorfield** [yogthos/Selmer#243]
I've often found that I've wanted to include section headings in loops when a particular subelement changes.

You can do this manually by passing `(map #(hash-map :current %1 :previous %2) data (cons nil data))` instead of just `data` and referring to `item.current.section` and `item.previous.section` inside your loop, but it would be nice if this was automatically available as `forloop.previous` (so you'd refer to `item.section` and `forloop.previous.section`).

Would you be interested in a PR for this?

**Comment by yogthos** [comment]
That sounds like it would be a useful enhancement, and a PR would be very welcome. The for loop handler [here](https://github.com/yogthos/Selmer/blob/aef8237bf36669f7da39cc3c49de0f68dfd70ee9/src/selmer/tags.clj#L38) is where you'd want to make the change.

**Comment by seancorfield** [comment]
One thing that may not be obvious (and it wasn't to me, until I actually started using it today at work!): `forloop.previous` is a hash map that contains the loop variable name:
```
{% for item in some.values %}
  {% if forloop.previous.item = item %}
  repeated
  {% else %}
  {{item}} is new!
  {% endif %}
{% endfor %}
```
