### ISSUE TITLE
Slow performance when using comparison operators referencing context map

### ISSUE THREAD

**Issue by rutchkiwi** [yogthos/Selmer#245]
Hi @yogthos !

I'm having some performance issues on my site and I've managed to trace them down to the selmer rendering. I'll show a condensed example of the issue:

```clojure
(dotimes [_ 5] (time (selmer/render "{% for p in list %}{% if p.a > p.b %}{% endif %}{% endfor %}"
                                    {:list (repeat 1000 {:a 156,
                                                         :b 0})})))
"Elapsed time: 147.766085 msecs"
"Elapsed time: 148.452832 msecs"
"Elapsed time: 124.380971 msecs"
"Elapsed time: 134.689312 msecs"
"Elapsed time: 138.402397 msecs"
```

If I don't reference p.a or p.b in the `if` tags, things are a lot faster:

```clojure
(dotimes [_ 5] (time (selmer/render "{% for p in list %}{% if 1 > 0 %}{% endif %}{% endfor %}"
                                    {:list (repeat 1000 {:a 156,
                                                         :b 0})})))
"Elapsed time: 31.924543 msecs"
"Elapsed time: 16.839626 msecs"
"Elapsed time: 18.267029 msecs"
"Elapsed time: 18.014365 msecs"
"Elapsed time: 13.113285 msecs"
```

In my real production example this is magnified many times as I've got loads of these comparisons, leading to template rendering completely dominating my response times. (~3000ms or so)

### Questions:

- First off, is my intuition correct in that it's too slow / a performance bug? 
- Secondly, do you have any guesses as to where the problem can be? If you don't, I can of course try and look into it myself but would appreciate any help / guidance!

Thanks!

**Comment by yogthos** [comment]
Hi,

I agree the performance hit is excessive here, so I'd consider it a performance bug. I don't have a guess as to what the specific cause for the issue would be, but [this](https://github.com/yogthos/Selmer/blob/deed36e2d8d67d5cd4f2cc226e59ddf2edb9252b/src/selmer/tags.clj#L38) wold be the spot to start. It would probably be easiest to do a bit of profiling to narrow down where specifically the slow down is happening. If you have time to take a look at this that would be much appreciated. :)

**Comment by rutchkiwi** [comment]
Thanks for the input. I will have a look.

While I'm running the tests I'm getting a bunch of reflection warnings:

```
Reflection warning, /private/var/folders/hk/ssb3bsh12bs8l3pd4wct1_0m0000gn/T/form-init17208303724063951205.clj:1:180 - reference to field getFileName can't be resolved.
Reflection warning, /private/var/folders/hk/ssb3bsh12bs8l3pd4wct1_0m0000gn/T/form-init17208303724063951205.clj:1:219 - reference to field getLineNumber can't be resolved.
Reflection warning, /private/var/folders/hk/ssb3bsh12bs8l3pd4wct1_0m0000gn/T/form-init17208303724063951205.clj:1:261 - reference to field getClassName can't be resolved.
Reflection warning, /private/var/folders/hk/ssb3bsh12bs8l3pd4wct1_0m0000gn/T/form-init17208303724063951205.clj:1:431 - reference to field getStackTrace can't be resolved.
Reflection warning, /private/var/folders/hk/ssb3bsh12bs8l3pd4wct1_0m0000gn/T/form-init17208303724063951205.clj:1:705 - reference to field getClassName can't be resolved.
Reflection warning, /private/var/folders/hk/ssb3bsh12bs8l3pd4wct1_0m0000gn/T/form-init17208303724063951205.clj:1:692 - call to method startsWith can't be resolved (target class is unknown).
Reflection warning, /private/var/folders/hk/ssb3bsh12bs8l3pd4wct1_0m0000gn/T/form-init17208303724063951205.clj:1:765 - reference to field getStackTrace can't be resolved.
Reflection warning, /private/var/folders/hk/ssb3bsh12bs8l3pd4wct1_0m0000gn/T/form-init17208303724063951205.clj:1:2287 - reference to field getName can't be resolved.
Reflection warning, /private/var/folders/hk/ssb3bsh12bs8l3pd4wct1_0m0000gn/T/form-init17208303724063951205.clj:1:4562 - reference to field flush can't be resolved.
```

Am I running the project in a funny way or is this to be expected?

**Comment by yogthos** [comment]
The reflection warnings are expected, mostly there to catch performance regressions.

**Comment by rutchkiwi** [comment]
Thank you, then I know I can ignore those. I will let you know what I find out!
