### ISSUE TITLE
Nested templates with with-clauses throws exception

### ISSUE THREAD

**Issue by rutchkiwi** [yogthos/Selmer#247]
After upgrading selmer to the latest version some of my templates new throw exceptions.

I've narrowed it down to the test case shown here: https://github.com/yogthos/Selmer/compare/master...rutchkiwi:include-with-broken

basically, nested includes error if the outer one has a with in it. Stack trace is shown below.

I believe this was introduced in version 1.12.29, when includes were reworked: https://github.com/yogthos/Selmer/pull/241 https://github.com/yogthos/Selmer/pull/242. Perhaps @mchughs has any ideas what the issue could be?

```
java.lang.Exception: unrecognized tag: :include - did you forget to close a tag?
 at selmer.parser$expr_tag.invokeStatic (parser.clj:155)
    selmer.parser$expr_tag.invoke (parser.clj:152)
    selmer.parser$parse_tag.invokeStatic (parser.clj:174)
    selmer.parser$parse_tag.invoke (parser.clj:170)
    selmer.parser$add_node.invokeStatic (parser.clj:286)
    selmer.parser$add_node.invoke (parser.clj:281)
    selmer.parser$parse_STAR_.invokeStatic (parser.clj:298)
    selmer.parser$parse_STAR_.invoke (parser.clj:288)
    selmer.parser$parse_input.invokeStatic (parser.clj:322)
    selmer.parser$parse_input.doInvoke (parser.clj:319)
    clojure.lang.RestFn.invoke (RestFn.java:423)
    selmer.parser$parse_file.invokeStatic (parser.clj:327)
    selmer.parser$parse_file.invoke (parser.clj:326)
    selmer.parser$parse.invokeStatic (parser.clj:357)
    selmer.parser$parse.doInvoke (parser.clj:329)
    clojure.lang.RestFn.invoke (RestFn.java:442)
    selmer.parser$render_file.invokeStatic (parser.clj:140)
    selmer.parser$render_file.doInvoke (parser.clj:122)
    clojure.lang.RestFn.invoke (RestFn.java:425)
    selmer.core_test$fn__25504.invokeStatic (core_test.clj:162)
    selmer.core_test/fn (core_test.clj:161)
    clojure.test$test_var$fn__9209.invoke (test.clj:716)
    clojure.test$test_var.invokeStatic (test.clj:716)
    clojure.test$test_var.invoke (test.clj:707)
    user$eval26953$fn__26992$fn__26993$fn__26994.invoke (form-init2718025410337559658.clj:1)
    clojure.test$default_fixture.invokeStatic (test.clj:686)
    clojure.test$default_fixture.invoke (test.clj:682)
    user$eval26953$fn__26992$fn__26993.invoke (form-init2718025410337559658.clj:1)
    clojure.test$default_fixture.invokeStatic (test.clj:686)
    clojure.test$default_fixture.invoke (test.clj:682)
    user$eval26953$fn__26992.invoke (form-init2718025410337559658.clj:1)
    clojure.core$with_redefs_fn.invokeStatic (core.clj:7434)
    clojure.core$with_redefs_fn.invoke (core.clj:7418)
    user$eval26953.invokeStatic (form-init2718025410337559658.clj:1)
    user$eval26953.invoke (form-init2718025410337559658.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:7062)
    clojure.lang.Compiler.eval (Compiler.java:7025)
    clojure.core$eval.invokeStatic (core.clj:3206)
    clojure.core$eval.invoke (core.clj:3202)
    clojure.main$repl$read_eval_print__8572$fn__8575.invoke (main.clj:243)
    clojure.main$repl$read_eval_print__8572.invoke (main.clj:243)
    clojure.main$repl$fn__8581.invoke (main.clj:261)
    clojure.main$repl.invokeStatic (main.clj:261)
    clojure.main$repl.doInvoke (main.clj:177)
    clojure.lang.RestFn.invoke (RestFn.java:1523)
    nrepl.middleware.interruptible_eval$evaluate.invokeStatic (interruptible_eval.clj:79)
    nrepl.middleware.interruptible_eval$evaluate.invoke (interruptible_eval.clj:55)
    nrepl.middleware.interruptible_eval$interruptible_eval$fn__2442$fn__2446.invoke (interruptible_eval.clj:142)
    clojure.lang.AFn.run (AFn.java:22)
    nrepl.middleware.session$session_exec$main_loop__2543$fn__2547.invoke (session.clj:171)
    nrepl.middleware.session$session_exec$main_loop__2543.invoke (session.clj:170)
    clojure.lang.AFn.run (AFn.java:22)
    java.lang.Thread.run (Thread.java:834)
```

**Comment by mchughs** [comment]
Hi rutchkiwi. I see in the test that you're using a syntax that I haven't seen anywhere in the docs or the tests.

If I look at examples of how `with` is supported I see for example `{% with total=business.employees|count %}{{ total }}{% endwith %}`

If your goal is to bind a value to variable and make it available in a deep nesting I would suggest the following set up if possible.

**grandparent.html**
```foo {% with my-variable="some-value" %}{% include "parent.html" %}{% endwith %}```

**parent.html**
```bar {% include "child.html" %}```

**child.html**
```baz {{ my-variable }}```

Then you should get something along the lines of  
```clojure
(render-file "grandparent.html" {})
;=> "foo bar baz some-value"
```

Let me know if that helps or if there is still a problem. If it does I can propose an MR which catches that edge case.

**Comment by rutchkiwi** [comment]
@mchughs Thanks for replying! :)

The with-in-include behavior is documented here: https://github.com/yogthos/Selmer#include. Although that syntax might be a bit funky since it doesn't do exactly the same thing as the with clause on it's own (it only sets a default filter on the variables listed) it is a documented behavior and used to work in versions < 1.12.29. 

For me personally I could probably change everything over to standalone with-clauses pretty easily, but I think it'd be better to fix the problem, so people don't get hit with a breaking change at a minor version upgrade.

I would really appreciate any help looking into this @mchughs

**Comment by mchughs** [comment]
Hi, sorry about that, you're right. I do see it mentioned in the docs.

And I do indeed get the `unrecognized tag: :include` error you mentioned when there are nested includes. I've confirmed it only becomes a problem when they are nested. I'm going to add some more tests.

I'll need some time to look through and understand how this special `with` form works/worked before.

**Comment by rutchkiwi** [comment]
You're a legend @mchughs! please let me know if I can be of any assistance.

**Comment by yogthos** [comment]
@mchughs thanks for taking a look, and I'll try assist if I can as well. :)

**Comment by mchughs** [comment]
Update: I think I have a rough MR on the way.

**Comment by mchughs** [comment]
Please take a look at https://github.com/yogthos/Selmer/pull/249 and see if works for you.

**Comment by yogthos** [comment]
Awesome, thanks for getting the lightning fast PR @mchughs. Just pushed out `1.12.33` to Clojars.

**Comment by rutchkiwi** [comment]
Mega big thanks @mchughs! That was impressive. And also @yogthos for the release. :)
