### ISSUE TITLE
Is it possible to split up an input via filter and address it by index?

### ISSUE THREAD

**Issue by sova** [yogthos/Selmer#251]
Imagine there is an input `"big;house;small;cat"`
I have a javascript function I'd like to pass `( "big", "house", "small", "cat" )`
I can create a filter to do `clojure.string/split s #";"`  on the  semicolons,
can I reference each of these variables now within an html template using selmer?

**Comment by yogthos** [comment]
It's not currently possible for filters to modify the context map. Is there a reason not to do the parsing before the data is passed to slemer?

**Comment by sova** [comment]
Okay, thanks.  I suspected so. 
In my particular case, I'm trying to create an easy and programmatic way to add interactive elements to pages, and right now the pages are represented as a vector of vectors.  For the most part, running filters on them works great, but in this case I want to pass some set of params to a javascript function to generate the interactive element.  I could probably approach this in clojurescript and grab the params from the server, but I was hoping I could just "hard code" it in to the page data in my current vector representation.

**Comment by yogthos** [comment]
One thing you could do would be to create a js variable on the page using a filter, and then read it with cljs on the client.

**Comment by sova** [comment]
That's an interesting idea!  Do you think putting something into a data-attrib on an html element and then using cljs.reader/read-string is a reasonable approach?  I have an array of strings, what do you think is the best way to plug them in to an html page ?

**Comment by yogthos** [comment]
I generally just create a script tag and create js variables there so I can skip having to parse them out, but using a data-attrib would work as well.
