### ISSUE TITLE
forloop.parentloop.counter not set

### ISSUE THREAD

**Issue by sova** [yogthos/Selmer#252]
```
  {% for p in rp %} 
        <div class='rk' >Snax.</div> 
        {% for rp-page in rp-pages %}
        <div> {{forloop.parentloop.counter}} :: {{forloop.counter}}</div>
         {% ifequal forloop.parentloop.counter forloop.counter %}
            <div> {{rp-page.0}} ::: {{rp-page.1}}</div>
         {% endifequal %}
        {% endfor %}
      {% endfor %}
```

`forloop.parentloop.counter` in the above does not return a result and is blank.

I thought parentloop.counter might be the way to go, but actually it also returns the same number as forloop.counter.  Pardon the confusion

My issue is that I have two equal lengths datasets and would like to make links to URLs provided by the one set and titles provided by the other set.  I thought it would be feasible to do an `ifequal forloop.parentloop.counter and forloop.counter` to get precisely N hits on an N x N for-for-loop.    Is it possible to achieve, what I'm trying to do here?

**Comment by sova** [comment]
I don't know if it's possible with Selmer, but I can consolidate the data before passing it to the render function, so it's not really a Selmer shortcoming.

**Comment by yogthos** [comment]
Yeah, consolidating ahead of time would probably be best.
