### ISSUE TITLE
Consider separating public and private API using :no-doc metadata

### ISSUE THREAD

**Issue by borkdude** [yogthos/Selmer#268]
When the string interpolation logic got added, `<<`, two more functions got added as well. I think they can be considered a private API. Marking them with `:no-doc` true makes this explicit (it won't show up in the API docs on cljdoc for example).
Consider doing this for more vars that were implemented in the past as well. This won't break any existing callers, but will communicate clearly what is considered the public API.

In babashka I'm leaving out automatically the vars that are marked with `:no-doc`.

**Comment by yogthos** [comment]
[this](https://github.com/yogthos/Selmer/commit/3387e76dc2325ab2cead5deb043fc2e729fadadc) should do the trick :)
