### ISSUE TITLE
for index in range

### ISSUE THREAD

**Issue by seancorfield** [yogthos/Selmer#274]
I often find myself wanting a `for` loop over a range of numeric values and it seems the only way to do that is to explicitly create the sequence of values in code and make it available to the template as data.

It would be nice to be able to specify the range sequence directly in the template instead. Something like:

```clojure
{% for index in range:99 %}
...
{% endfor %}
```

And for it to work with all three arities of `range`.

**Comment by yogthos** [comment]
I agree that would be a useful feature. I'll take a look at it when I get a chance, but if you'd be up for doing a PR [this](https://github.com/yogthos/Selmer/blob/master/src/selmer/tags.clj#L38) would be the place to look. It shouldn't be too hard to add support for having ranges there.

**Comment by seancorfield** [comment]
Any preference on syntax? There's no precedent for my suggestion -- I was just trying to pick something that wouldn't match existing legal syntax. This would sort of make `range:` a special thing on its own.

I'll have a think about it and may drop some additional suggestions in here.

It would be nice if `range` was just a filter but I'm not sure what you'd apply it to here, with potentially three arities.

**Comment by seancorfield** [comment]
I added a `:range` filter locally to play with syntax. Interestingly, `{{9|range}}` works but not `{% for i in 9|range %}` -- only a varname works there:
```clojure
dev=> (p/render "{{n|range}}" {:n 20})
"(0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19)"
dev=> (p/render "{{9|range}}" {})
"(0 1 2 3 4 5 6 7 8)"
dev=> (p/render "{{9|range:1}}" {})
"(1 2 3 4 5 6 7 8)"
dev=> (p/render "{{9|range:1:2}}" {})
"(1 3 5 7)"
dev=> (p/render "{% for i in 9|range:1:2 %}i={{i}}; {% endfor %}" {})
""
dev=> (p/render "{% for i in n|range:1:2 %}i={{i}}; {% endfor %}" {:n 20})
"i=1; i=3; i=5; i=7; i=9; i=11; i=13; i=15; i=17; i=19; "
```

**Comment by yogthos** [comment]
Yeah,`for` parser doesn't consider literals at the moment. The fix would be to use a regex to check if the the value is a number and parse it directly instead of treating it as a key for the context.

**Comment by seancorfield** [comment]
I guess I was just a bit surprised it worked as an expression outside of `for` -- and then more surprised that `{{foo|bar}}` and `{% for x in foo|bar %}` did not work the same way 😄

**Comment by yogthos** [comment]
There are definitely some rough edges there. :)

**Comment by seancorfield** [comment]
Thank you! I tried to cover docs and tests in the PR.
