### ISSUE TITLE
`render` fails with `include` tag

### ISSUE THREAD

**Issue by crinklywrappr** [yogthos/Selmer#278]
`render` throws an exception w/ an `include` tag in the string on the latest version.

```clojure
(sr/render "{% :include \"foo.bar\" %}" {})

;=>
; Execution error at selmer.parser/expr-tag (parser.clj:159).
; unrecognized tag: ::include - did you forget to close a tag?
```

`render-file` works with the `include` tag, however.

**Comment by yogthos** [comment]
Include tag is only implemented for files since it inherently operates on files, so that's expected behavior. The `render` function doesn't do any IO, so it wouldn't really make sense to implement `include` in that context. I'm open to ideas if I'm missing something here though. :)

**Comment by crinklywrappr** [comment]
I wrote this tag to include hiccup templates.  The idea is that things further nested (like CSS, js, etc) will cause `hiccup.core/html` to throw an exception, so the translation to HTML needs to happen before Selmer walks deeper into the render stack.

```clojure
(def tmpdir (io/file ".tmp/"))

(defn mktemp [suffix]
  (str (java.io.File/createTempFile "wordlsolver" suffix tmpdir)))

(add-tag! :includehiccup
   (fn [[file & [options]] context-map]
     (let [tmp (mktemp (sg/replace file "." ""))
            x (spit tmp (html (edn/read-string (slurp file))))]
       (render-file tmp context-map))))
```

But I ran into some surprises

1. I didn't expect that a call to `render` or `render-file` would be necessary within the tag handler.
2. `hiccup.core/html` returns a string, and I didn't expect that would be a problem.  To mitigate I have to make a temp file.  Seems unecessary.

**Comment by yogthos** [comment]
If you're using a custom tag to load content from files that shouldn't be a problem. You just can't use the builtin `include` tag along with `render`. So, I think the solution would be to make a tag like `:includehiccup` and use it any time you're loading content.

**Comment by crinklywrappr** [comment]
If I develop another static site generator, the docs will need to warn users not to use the include tag.
