### ISSUE TITLE
Clojure 1.11 preparations - parse-double

### ISSUE THREAD

**Issue by ieugen** [yogthos/Selmer#280]
Updating to clojure 1.11.0-rc1 gives this warning:

```
; WARNING: parse-double already refers to: #'clojure.core/parse-double in namespace: selmer.tags, being replaced by: #'selmer.tags/parse-double
```

**Comment by yogthos** [comment]
That should be fixed in the latest version [here](https://github.com/yogthos/Selmer/blob/4552debc83e65ccdcb1c4a9b3eb53513d2104940/src/selmer/tags.clj#L114).
