### ISSUE TITLE
[Request] Add the ability to not escape all characters

### ISSUE THREAD

**Issue by davidginzbourg** [yogthos/Selmer#282]
```clojure
(require '[selmer.parser :as strf])
(strf/render "{{a}} {{b}}"
             {:a "123&"
              :b "c = ''"})
;; => "123&amp; c = &#39;&#39;"

(strf/render "{{a}} {{b}}"
             {:a "123&"
              :b "c = ''"}
              {:all-safe true})
;; => "123& c = ''"

(strf/render-safe "{{a}} {{b}}"
             {:a "123&"
              :b "c = ''"})
;; => "123& c = ''"
```

Do you think it's viable? Or fits this library? The goal is to prevent escaping characters in cases where this lib is used for string formatting but not in the context of HTML.

Let me know what do you think, thank you!

**Comment by davidginzbourg** [comment]
I see there's already an MR for it: https://github.com/yogthos/Selmer/pull/98/files

**Comment by davidginzbourg** [comment]
In the last part of https://github.com/yogthos/Selmer#filters

It is possible to disable escaping (if, for example, your target format is not HTML/XML) using the selmer.util/without-escaping macro:
```clojure
(require '[selmer.util :refer [without-escaping]])

(without-escaping
  (render "{{x}}" {:x "I <3 NY"}))
=>"I <3 NY"
```
Alternatively, you can turn off escaping permanently in all threads with the `selmer.util/turn-off-escaping!` function.

**Comment by yogthos** [comment]
Yeah that's the way to control escaping currently. It's also possible to do via filters:

```clojure
(add-filter! :foo  (fn [x] [:safe (.toUpperCase x)]))

(render "{{x|foo}}" {:x "<div>I'm safe</div>"})
=>"<DIV>I'M SAFE</DIV>"
```

I'd be open to passing an option for doing more granular escaping to provide more granular control. Perhaps something like the following:

```clojure
(strf/render "{{a}} {{b}}"
             {:escaped-characters
              {:a "123&"
               :b "c = ''"})
```

Then when `escaped-characters` key is present it would override default behavior.

**Comment by davidginzbourg** [comment]
Thanks!
I just didn't search the right keywords when I was searching the documentation.
Found the `|safe` and `:safe`, filter and control option, but didn't find the other global options until I searched the issues

**Comment by yogthos** [comment]
Ah gotcha, glad everything works 👍
