### ISSUE TITLE
Would you consider adding something like known-variables-and-keys?

### ISSUE THREAD

**Issue by endrebak** [yogthos/Selmer#283]
Selmer can render nested maps:

```
(use 'selmer.parser)
(def e "we are {{hi.there}} boo§ {{hullo.there.again}}")
(render e {:hi {:there "a"} :hullo {:there {:again "c"}}})
=> "we are a boo§ c"
```

It would help me so much if Selmer could also give me the required keys for each template string:

```
(known-variables-and-keys e)
[[:hi :there] [:hullo :there :again]
```

In the above each `vec` could be used with `get-in`.

Would you consider adding something like this?

**Comment by yogthos** [comment]
I wouldn't be opposed to the feature. Would you be up for taking a shot at implementing it?

**Comment by endrebak** [comment]
Eventually, yes, but I am busy atm. I will just use a regex for now.

**Comment by yogthos** [comment]
I think it might be best to extend [parse-variables](https://github.com/yogthos/Selmer/blob/d9a4d700323d2d8ba93edd833ab73a177bbc0f4d/src/selmer/parser.clj#L365) to handle keys as well, and then leverage the output from that.

**Comment by boxxxie** [comment]
i decided to give this a try, and it turned out to not be too hard.
the code is pretty bad, but i didn't want to rewrite the parse-variables function. i still don't really know how it works :)

**Comment by yogthos** [comment]
I think that's reasonable enough, and gets the job done. Just pushed out `1.12.53` with the fix. Thanks for spearheading this. @endrebak does the fix look reasonable enough to address the original issue?

**Comment by endrebak** [comment]
Feel free to close. I wont have the time to look at this for a while :/
