### ISSUE TITLE
escaping nested references

### ISSUE THREAD

**Issue by trevor** [yogthos/Selmer#30]
Would it be possible to accommodate keywords that contain dots? I have several Datomic entities that have these and it would be nice to reference them directly instead of creating intermediaries. Maybe with an alternate syntax from `{{` / `}}`? `{{. my.item/sub.thing .}}` ?

**Comment by zuriar** [comment]
Hi - has this functionality been implemented yet?

**Comment by yogthos** [comment]
I haven't worked on this yet myself.

**Comment by zuriar** [comment]
Hi - just submitted pull request with a fix. I have used a 'double dot' to indicate not to split. Thanks, Hugh

**Comment by yogthos** [comment]
Perfect, I just merged it in, I'll get a new release to Clojars shortly. I'm traveling at the moment, so might be a week or so. :)

closed by https://github.com/yogthos/Selmer/pull/120
