### ISSUE TITLE
Chinese locale date tests fail locally

### ISSUE THREAD

**Issue by seancorfield** [yogthos/Selmer#302]
```
FAIL in (filter-date) (core_test.clj:879)
expected: (= "上午12:00" (render "{{d|date:shortTime:zh}}" {:d firstofmarch}))
  actual: (not (= "上午12:00" "00:00"))

lein test :only selmer.core-test/filter-date

FAIL in (filter-date) (core_test.clj:883)
expected: (= "2014/3/1 上午12:00" (render "{{d|date:shortDateTime:zh}}" {:d firstofmarch}))
  actual: (not (= "2014/3/1 上午12:00" "2014/3/1 00:00"))
```

I haven't dug into _why_ these fail for me -- just wanted to get this on the record.

**Comment by yogthos** [comment]
I'm seeing it locally as well actually. I wonder if it's a change in the latest JDK?

**Comment by yogthos** [comment]
Ok, confirmed that I'm seeing original behavior with JDK 17, and new behavior with 19. I decided to update the test to match whatever the latest JDK expects. I think this is ultimately out of purview of the library since the functionality is delegated to the date time formatter in the JDK.

**Comment by seancorfield** [comment]
Yeah, at work we have some formatting tests around non-breaking whitespace and they broke with nearly every JDK update for a while (from 8 to 14, but they've been stable since then).

**Comment by yogthos** [comment]
I've come to think of the JVM as having rock solid backwards compatibility, so always get blindsided when they break it in weird ways. :)
