### ISSUE TITLE
Updating filters requires restarting clojure to take effect

### ISSUE THREAD

**Issue by boxxxie** [yogthos/Selmer#305]
when i use add-filter multiple times (updating a named filter's behaviour) i don't see the changes reflected in my rendered templates until i restart my server.

has anyone else run into something like this? i'm wondering if i'm using selmer incorrectly.

template caching is disabled

example filter code, nothing special
```clojure
(selmer.filters/add-filter! :meta
  (fn [obj] (meta obj)))
```

my render function:
```clojure
(defn render-file
  ([file-name] (render-file file-name {}))
  ([file-name obj]
   (trace "selmer render" file-name)
   (selmer.parser/render-file file-name (assoc obj :true true :false false))))
```

selmer version 1.12.53

**Comment by yogthos** [comment]
Filters are an atom found in `selmer.filters/filters`, so there shouldn't be anything special happening there. However, if the `render-file` is called from the routing library it may have a stale version of the function.
