### ISSUE TITLE
Could date filter support Instant?

### ISSUE THREAD

**Issue by seancorfield** [yogthos/Selmer#308]
The code for `java.util.Date` arguments goes through `Instant` to get to a local date/time so it seems like `java.time.Instant` could be supported this way too:

```clojure
        (instance? java.util.Date d)
        (-> (.toInstant ^java.util.Date d)
            (.atZone (ZoneId/systemDefault))
            (.toLocalDateTime))
```
as:
```clojure
        (instance? java.time.Instant d)
        (-> (.atZone ^java.time.Instant d (ZoneId/systemDefault))
            (.toLocalDateTime))
```

I was a bit surprised this wasn't already supported when I got "Execution error (IllegalArgumentException) at selmer.filters/fix-date (filters.clj:75).
2024-05-30T18:54:50.768632311Z is not a valid date format."

I also noticed that the comment on the `|date` filter talks about Joda Time... which isn't supported by Selmer any more, right?

**Comment by yogthos** [comment]
Oh yeah, code got updated to use Instant, but looks like the doc string never got updated. I agree with supporting `Instant` along with `Date`.

**Comment by seancorfield** [comment]
OK, will work on a PR...

**Comment by yogthos** [comment]
Oh, I just pushed up `1.12.60` with the fix. :)

**Comment by yogthos** [comment]
But if there's anything else you'd like to add PR is welcome as well.

**Comment by yogthos** [comment]
and pushed up `1.12.61` with your changes added in, thanks for the quick PR
