### ISSUE TITLE
`extends` from `render` throws an error

### ISSUE THREAD

**Issue by teotenn** [yogthos/Selmer#310]
I have the template `selmer.html`:

```
<html>
  <h1>A title</h1>
  <div>
    {% block content %}
    {% endblock %}
  </div>
</html>
```

If I `extends` it from another template everything works well:

```
{% extends "selmer.html" %}
{% block content %}
<h2>Subtitle</h2>
<p>A paragraph</p>
{% endblock %}
```

Then `render-file` returns what I would expect. But if I call exactly the same from a string using `render` I get an error

```
(def x "{% extends \"selmer.html\" %}
{% block content %}
<h2>Subtitle</h2>
<p>A paragraph</p>
{% endblock %}
")

(selmer/render x {})
```

*Execution error (ExceptionInfo) at selmer.parser/expr-tag (parser.clj:160).
unrecognized tag: :extends - did you forget to close a tag?*

Am I missing something? Is that the expected behavior? If so, how can I extend from within clojure (I would guess using string, but I am open to other options) without having to use a separate template that calls `extends`?

**Comment by yogthos** [comment]
That's expected behavior because `render` simply considers the text in the string that's passed to it. If you need to use `extends` then you have to use file based templates.

**Comment by teotenn** [comment]
Ok thanks, I'm closing this issue then and I'll try to work with what you guys have.

As a suggestion, it would be nice to include it in the documentation, maybe in the way you have it for `include`:

"This tag is only available for `render-file`"

**Comment by yogthos** [comment]
Good idea, I've added a note under template inheritance to clarify the behavior.
