### ISSUE TITLE
The currency-format filter is using the Unicode generic currency symbol

### ISSUE THREAD

**Issue by edorrington** [yogthos/Selmer#70]
If I (in the U.S.) attempt to use the currency-format filter, instead of using a dollar sign, the filter is formatting the number using the Unicode generic currency symbol, ¤ (\u00A4). Poking around the source, you're passing the NumberFormat getCurrencyInstance method a locale that's constructed by just giving the language code with a default language of "en". In that case the format method is using the generic currency symbol. If instead you pass a locale that is constructed using the language code "en" and country code "US", then it correctly uses the dollar sign.

**Comment by yogthos** [comment]
thanks for the suggestion, just pushed out a new version to Clojars, the formatter will now also take an optional country code, eg:

```clojure
(render "{{f|currency-format:de:DE}}" {:f 123.45})
```

**Comment by edorrington** [comment]
Dmitri,

Thank you for the quick response! I'm really enjoying using Selmer, by
the way.

--Ed

**Comment by yogthos** [comment]
glad to hear it :)
