### ISSUE TITLE
  {% include "..l" with name="{{control-name}}" %}

### ISSUE THREAD

**Issue by bherrmann7** [yogthos/Selmer#75]
Wish I could do this

  {% include "templates/picker.html" with name="{{control-name}}" %}

but it seems the arguments passed to include arent allowed to be dynamic...  right?

**Comment by yogthos** [comment]
That's correct, for that you have to use the [with](https://github.com/yogthos/Selmer#with) tag tha gets evaluated at runtime. Not as nice, but for memoization the templates have to be merged at compile time.

**Comment by danielflower** [comment]
Thanks, this helped a lot. But is this the best way to make server side components with Selmer?

**Comment by yogthos** [comment]
If you need to set some dynamic variables for a specific scope then it's the way to do it. The other option is to simply pass them directly in the parameter map.
