### ISSUE TITLE
compiler warning: *custom-resource-path* not declared dynamic

### ISSUE THREAD

**Issue by gws** [yogthos/Selmer#77]
I'm using `0.8.1`. Looks like this was caused by #76.

```
Warning: *custom-resource-path* not declared dynamic and thus is not dynamically rebindable, but its name suggests otherwise. Please either indicate ^:dynamic *custom-resource-path* or change the name. (selmer/util.clj:11)
```

**Comment by yogthos** [comment]
Thanks, I added the dynamic annotation for it, `0.8.2` shouldn't give the warning anymore. As a long term solution, I'd rather get rid of the dynamic var all together and simply allow passing the resource path in opts.
