### ISSUE TITLE
Selmer creates empty tags for unfulfilled if clauses

### ISSUE THREAD

**Issue by venantius** [yogthos/Selmer#80]
This is a bit of a weird bug. I've got a template right now that contains the following:

```html
{% ifequal user.task|last task %}
<td width="32" background="">
{% else %}
<td width="32" background="https://s3-us-west-2.amazonaws.com/ursacorp-cloudfront-assets/email/bg.jpg">
{% endifequal %}
```

If the first condition isn't satisfied, Selmer inserts a `</td>` tag as well as inserting the contents from the `else` clause. This turns out not to be a problem with most browsers, but wreaks havoc on Gmail, which is unfortunately the targeted renderer here. Happy to provide more info if needed.

**Comment by yogthos** [comment]
Selmer isn't actually HTML aware at all, so it doesn't attempt to parse or insert tags. It only does straight up text replacement for its own tags. Something else must be happening here. :)

**Comment by venantius** [comment]
Question, then: hypothetically, would you agree that 

```html
{% ifequal user.task|last task %}
<td width="32" 
background="https://s3-us-west-2.amazonaws.com/ursacorp-cloudfront-assets/email/bg.jpg">
{% else %}
<td width="32" 
background="https://s3-us-west-2.amazonaws.com/ursacorp-cloudfront-assets/email/bg.jpg">
{% endifequal %}
```
should always evaluate to 

```html
<td width="32" 
background="https://s3-us-west-2.amazonaws.com/ursacorp-cloudfront-assets/email/bg.jpg">
```
?

**Comment by yogthos** [comment]
That indeed should be the case, I'm also not able to reproduce this problem locally, with the original template:

```xml
{% ifequal user.task|last task %}
<td width="32" background="">
{% else %}
<td width="32" background="https://s3-us-west-2.amazonaws.com/ursacorp-cloudfront-assets/email/bg.jpg">
{% endifequal %}
```

```clojure
(render-file "template.html"
             {:task 3
              :user {:task [1 2 3]}})
```
```
"\n<td width=\"32\" background=\"\">\n\n"
```
```clojure
(render-file "template.html"
             {:user {:task [1 2 3]}})
```
```
"\n<td width=\"32\" background=\"https://s3-us-west-2.amazonaws.com/ursacorp-cloudfront-assets/email/bg.jpg\">\n\n"
```

**Comment by venantius** [comment]
Yeah, I think you may be right. I'm stripping out my stylesheets and trying to get to the root of this. Doesn't seem to be Selmer. Sorry for the false flag :)

**Comment by yogthos** [comment]
no worries
