### ISSUE TITLE
How to have custom Selmer tag return safe string?

### ISSUE THREAD

**Issue by limist** [yogthos/Selmer#81]
When using a Selmer custom tag via `add-tag!` that returns a string, is there a way to mark that returned string as safe?  

Putting the returned string inside a vector `[:safe foo-str]` just shows the literal vector after template rendering.  Couldn't see an example of this use-case in docs/tests, but maybe I'm missing something, thanks in advance for any tips/advice.

**Comment by yogthos** [comment]
You should be able to use the `|safe` filter for the variables as you would normally, eg:

```clojure
(add-tag! :uppercase
          (fn [args context-map content]
            (.toUpperCase (get-in content [:uppercase :content])))
          :enduppercase)

(render "{% uppercase %}foo {{bar|safe}} baz{% enduppercase %}" {:bar "<p>injected</p>"})
=>"FOO <P>INJECTED</P> BAZ"
```

**Comment by limist** [comment]
Thanks - what if the custom tag is a self-closing tag, such as `{% translate :english/hello-txt %}`  ?  Seems the `safe` filter can't be used in that case?

**Comment by yogthos** [comment]
The arguments are passed to tags as strings, and the result of custom tags isn't escaped, so if you wanted a tag to read something from the context map you could do:

```clojure
(add-tag! :translate
  (fn [args context-map]
    (-> args first keyword context-map)))

(render "{% translate text %}" {:text "<p>foo</p>"})
=>"<p>foo</p>"
```

**Comment by limist** [comment]
Belated thanks, figured out the problem: if using the taoensso/tower library, translated strings are escaped by default, see https://github.com/ptaoussanis/tower
