### ISSUE TITLE
keywords in ifequal

### ISSUE THREAD

**Issue by sonwh98** [yogthos/Selmer#82]
how can I use keywords in an ifequal comparision like this

{% ifequal project.status :done %}
  project is done
{% endifequal %}

status is a keyword but :done here does not seem to be treated like a keyword

**Comment by yogthos** [comment]
keywords aren't supported in ifequal currently

**Comment by sonwh98** [comment]
thanks for responding. I'll create a custom tag for this

**Comment by yogthos** [comment]
probably the simplest route :)
