### ISSUE TITLE
Is dynamic keyname supported?

### ISSUE THREAD

**Issue by zweifisch** [yogthos/Selmer#84]
something like `(let [key :name] (render "{{person[key]}}" {:person {:name "John Doe"}}))`

**Comment by yogthos** [comment]
Unfortunately it's not and no current plans to add that feature.

**Comment by zweifisch** [comment]
I tied to use a custom filter as a workaround, and just fund out that no white space is allowed before and after "|" :scream:

**Comment by yogthos** [comment]
that is the syntax :)

**Comment by yogthos** [comment]
I'm going to close this one as it sounds like you've got a solution via filter here.
