### ISSUE TITLE
error in if

### ISSUE THREAD

**Issue by QinAIns** [yogthos/Selmer#85]
1.When I test this:

	(parser/render "{% if now >= current %}yes!{% else %}no!{% endif %}" {:current  System/currentTimeMillis) :now (System/currentTimeMillis)})

it shows the error:
NumberFormatException For input string: "current"  sun.misc.FloatingDecimal.readJavaFormatString (FloatingDecimal.java:2043)

2.When I test this:

	(parser/render "{% if 1 > 0 %}yes!{% else %}no!{% endif %}" {})
	(parser/render "{% if 1 < 0 %}yes!{% else %}no!{% endif %}" {})

All show "no1". Orz

**Comment by yogthos** [comment]
The first arg in the if has to be a variable as it makes no sense to compare two constants:

```clojure
(render "{% if a > 0 %}yes!{% else %}no!{% endif %}" {:a 1})
```

**Comment by QinAIns** [comment]
Is the second arg in the if not be a variable in the 1st case? Sometimes I have 2 args, I don't want to compare them in the clojure code.

**Comment by yogthos** [comment]
The second parameter is meant to be a constant at the moment. As a rule, Selmer discourages putting logic in the templates. In my view it's better to do the comparison in code and then bind the result to a descriptive key in the parameter map.

**Comment by QinAIns** [comment]
Thanks.
