### ISSUE TITLE
unable to use add filter for Numbers

### ISSUE THREAD

**Issue by fzakaria** [yogthos/Selmer#86]
Anytime i try a filter such as `{{paginate.page|add:-1}}`

I get the following error:

`On filter body 'paginate.page|add:-1' and filter 'add:-1' this error occurred:java.lang.Long cannot be cast to java.lang.String`

Based on the docs it looks like the function should be performing the numerical add (vs string concat) for this case.

**Comment by yogthos** [comment]
I can reproduce this and looks like a bug, will take a look

**Comment by yogthos** [comment]
just pushed out a new release with the fix `0.8.5`, and added a test

**Comment by fzakaria** [comment]
thanks for the speedy response
