### ISSUE TITLE
How to combine increment two variables? (use variable in filter)

### ISSUE THREAD

**Issue by fzakaria** [yogthos/Selmer#88]
I have a sample web app where I am paginating the results.
I am using the 'forloop' construct however I'd like to print the appropriate result set number.
 
Ultimately, I'd like to do:
{{forloop.counter}} + {{offset}}

I can't seem to nest variables in filters?
{{forloop.counter|inc:{{offset}}} }}

**Comment by yogthos** [comment]
Yeah, default filters don't support this behaviour, you could write a custom tag for this however.

**Comment by fzakaria** [comment]
Here is what I used and it seemed to work.
Perhaps you can give me your opinion on it (+ writing it here for anyone also curious)

Here is the add tag:

    (parser/add-tag! :add
        (fn [args context-map]
            (reduce + (map (fn [val]
               (let [accessor (filter-parser/split-filter-val val)]
                 (get-in context-map accessor))) args))))

Here is where the HTML might work:

        {% for user in users %}
            <tr>
                <td>{% add forloop.counter paginate.offset %}</td>
                <td>{{user.email}}</td>
                <td><a href={{servlet-context}}/users/{{user.id}}>view</a></td>
            </tr>
        {% endfor %}

**Comment by yogthos** [comment]
That looks perfectly reasonable to me.

**Comment by fzakaria** [comment]
Okay great. We can close issue. 
Does that as a tag interest you at all in a PR ?
(Could call it "sum")

**Comment by yogthos** [comment]
Yeah, it does look like it would be a useful addition, if you'd like to make a PR I can release it. :)
