### ISSUE TITLE
Neither CHANGES.md nor Git tags

### ISSUE THREAD

**Issue by hlship** [yogthos/Selmer#93]
Please consider adding a CHANGES.md file, to identify when releases occur and what's changed in them.  Also, please tag your releases. It is very valuable to those of us upgrading from an old version to a new.

Thanks!

**Comment by yogthos** [comment]
I'll try to get in a habit for that, the good news is that there haven't been any breaking changes so far. At this point the core API is stable and the changes are either bug fixes or new features.

**Comment by yogthos** [comment]
tagged the last two releases, will make sure to tag for any breaking changes
