### ISSUE TITLE
See all variables in context?

### ISSUE THREAD

**Issue by terhechte** [yogthos/Selmer#94]
Is there a way to show everything that's registered in the context from within the template?

i.e. something like:

``` html
<ul>
{% for item in items %}
<li>{{item|str}}</li>
{% endfor %}
```

**Comment by yogthos** [comment]
The easiest way would be to write a custom tag, something like this should work:

```clojure
(add-tag! :debug
  (fn [args context-map]
    (str "<pre>" (with-out-str (clojure.pprint/pprint context-map)) "</pre>")))
```

**Comment by yogthos** [comment]
added the `debug` tag in `0.8.9` as a standard tag

**Comment by terhechte** [comment]
Awesome! Fantastic! Thanks.
