### ISSUE TITLE
Issue adding defaults to variables when using non-default filter chars

### ISSUE THREAD

**Issue by mackram** [yogthos/Selmer#96]
If you try to use a filter close that is different then the tag close then the include tag is not able to properly generate defaults. Please refer to suggested pull request for a solution.

PS thanks for the beautiful library.

**Comment by yogthos** [comment]
Thanks, the fix looks good, I just pushed a new version to Clojars with it.

**Comment by mackram** [comment]
Thanks for being so quick about this. I am going to close the issue.
