### ISSUE TITLE
Dynamic var to turn off HTML escaping

### ISSUE THREAD

**Issue by cpmcdaniel** [yogthos/Selmer#97]
I would like to be able to use Selmer for templating non-HTML formats. The only thing missing to make this a reality is a way to turn off the default behavior of HTML escaping the template values (I do not want a template full of {{x|safe}} filtered variables).

If I submitted a pull request to add such a dynamic var, would you accept it?

**Comment by yogthos** [comment]
I don't see a problem with turning off escaping as opt-in by the user and this wouldn't affect the default behavior. A pr for this would be great. :)

**Comment by cpmcdaniel** [comment]
Why is the latest version 9.0.0, but project.clj in master is set to 0.8.9? Not sure how I should submit my PR.

**Comment by cpmcdaniel** [comment]
PR submitted. You can close this once it's merged.

**Comment by yogthos** [comment]
closed with https://github.com/yogthos/Selmer/pull/98
